### ISSUE TITLE
Code Blocks in Flexdown?

### ISSUE THREAD

**Issue by Bluemoondragon07** [jmouka/flexdown-obsidian-plugin#3]
Hi! Thank you so much for making this plug-in--it's a lot easier and more flexible than the other column-layout plug-ins!

Do you know if there's any possible way to render code blocks inside a flexdown layout? It's probably impossible since the layout *is* a code block, but in my case I wanted to render a dataview list and a page gallery block side by side in a flexdown layout. I was wondering if an alternative to backticks could be used to produce a code block inside flexdown, but even if there isn't one, that's fine. Thanks for this amazing plug-in!

**Comment by jmouka** [comment]
I can't think of a way! Yeah that would be cool, I get what you're trying to do, but I can't think of a way to do it. That's the limitation of a plugin based on code blocks.

**Comment by Bluemoondragon07** [comment]
Yeah, probably not possible inside code blocks.

I've been thinking about this, though—is there a way to make the plugin target the whole note (except frontmatter), rather than just what's in the code block? Like, maybe any `|` or `---` in the body of the note could count as flexdown syntax?

I'm not sure if this is possible either, but it'd be cool. Maybe there could be a setting to treat the whole note as flexdown, or it could be enabled in the frontmatter with `flexdown: true` or something. Then maybe code blocks could be renderable. 

This could also ensure that the markdown remains markdown when opened in other softwares. By that I mean, not wrapped in code.

**Comment by Bluemoondragon07** [comment]
Hey, I found a way to do it! I don't know why I didn't think of this immediately, but I found that you can put codeblocks within codeblocks by increasing the number of backticks in the first codeblock.

````````
````flexdown

```
I am a codeblock.
```

````

````````

Four backticks for the flexdown codeblock, three backticks for a codeblock inside flexdown. It works!
